### ISSUE TITLE
Den 56 on Plugin Rare/Common Table Swap

### ISSUE THREAD

**Issue by crzyc** [Leanny/PKHeX_Raid_Plugin#12]
Title.

**Replicating:**
1. Use PKHeX / Wishing Piece on Plugin Den 56.
2. See Serebii's [encounter table](https://www.serebii.net/swordshield/maxraidbattledens.shtml). Serebii Den 36 and Serebii Den 63, for your convenience.
3. Check if the pokemon is identical on both Serebii Den 36 and Serebii Den 63. If so, perform a species reset. If not, continue.
4. Dump your save file, and look at the pokemon in the raid plugin. If the den is rare, then the plugin shows a common raid pokemon in the same slot, and vice versa.

**Additional Notes:**
I'm not sure if this applies to other dens as well. More research is required.

**Updates:**
1. This seems to be the case with Plugin Den 79, where Serebii Den 36's encounters are swapped with Serebii Den 63's, but not with Serebii Den 88's.

**Comment by Leanny** [comment]
Thank you, I will fix this in the next release
