### ISSUE TITLE
Watchtower (Dynamax Crystal Den) Missing/Not Missing (Den 16 actually missing)

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/PKHeX_Raid_Plugin#13]
Hello Leanny,

I noticed the Watchtower den which can only be activated with Dynamax Crystals (aka DLC) is not currently in the Display Raids list. The datamine of the latested Nest Report datamine confirm we will be receiving the 3rd Dynamax Crystal (DLC) shortly.

Will be den location be added to plug-in at some point?

**Comment by Leanny** [comment]
Hi. This den requires more research, as it has different mechanics from the normal ones (i.e. IVs for specific slots are fixed and others). As soon as I finished my research I will add it

**Comment by Th3Alic3** [comment]
Would providing any sample saves help?

**Comment by Leanny** [comment]
No it's fine, I am just not able to do any research before new year. After that I will start with my research and implement the special den

**Comment by Th3Alic3** [comment]
<img width="548" alt="1" src="https://user-images.githubusercontent.com/57371173/71632153-d3c7f180-2bc1-11ea-9c4d-cbfc3f9aa095.PNG">
<img width="545" alt="2" src="https://user-images.githubusercontent.com/57371173/71632154-d4f91e80-2bc1-11ea-869f-65b7d85c1ba9.PNG">

For anyone reading this:

The difference starts at Den 16/17. For the Raid Viewer to be correct, the Raid Viewer would have to show 100 Dens (not 99) as the broken down Watchtower for DLC Raid Crystals is in that 100. Without that placeholder, every Raid past 16, is 1 number higher than the actual.

Also, the Den just north of the tower, isn't actually showing in the Raid Viewer currently as a result of this mix-match.

**Comment by Th3Alic3** [comment]
Hey Leanny,

I know that there's delays with working on the Watchtower but would you re-add the missing Den and fix the numbering (by adding a placeholder of some-sort for the DLC Den)? Sometime soonish?

Thanks

**Comment by Leanny** [comment]
Den 16 was skipped on purpose as its the event den. I will have a new version ready early next year, probably tomorrow or the day after.

**Comment by Th3Alic3** [comment]
You appear to have this backwards.

I have a clear image of the Den 16 active but according to the Raid Viewer there are no active Dens ranged #10 to #20 in my save. Where's Den 16 in Raid Viewer?

Den #17 is the Watchtower Den!

You may be showing the correct Nests for #16 in the Raid Viewer but as you can see from the SEED, the Raid Viewer is clearly showing the Watchtower Den (#17) in the Raid Viewer's #16 slot.

I am saying your Raid Viewer is NOT showing Den (#16) at all.

**Comment by Leanny** [comment]
Ah sorry for misunderstanding. I will fix this in the next version as well!

**Comment by Th3Alic3** [comment]
Thanks!!

_(I cannot wait for your drop down to show 100 instead of 99! I know you may not have it all figured out thus far but for those of us with back-ups with these Dynamax Crystals... being able to see the Shiny Frame Advancement is huge. Even if we are unsure how to advance it.)_
