### ISSUE TITLE
the different between your plugin and pkhex in den

### ISSUE THREAD

**Issue by gjfkkk** [Leanny/PKHeX_Raid_Plugin#15]
the den16 in pkhex's raid is the one for the guys who buy doublepeck to get jangmo-o.but in your plugins this den is ghost.so we can't match the number from den16

**Comment by Leanny** [comment]
See issue #13

**Comment by Th3Alic3** [comment]
Hey @Leanny,

The games code has reservation for 111 Dens. There are only 99 on the map plus the DLC location of the broken down Watchtower.

The Raid Viewer currently shows listings for 99 locations.

- Den #16 (as numbered by Raid Plugin) is the broken down Watchtower (NOT a Map Den)
- Den #16 (as numbered by PKHeX) just north (only Den that spawns rare Nest 47) is MISSING from the Raid Viewer
- Den #17 (as numbered by PKHeX) is the broken down Watchtower

I have confirmed the SEEDs against the Raid Viewer and the PKHeX's Den Editor.

<img width="548" alt="1" src="https://user-images.githubusercontent.com/57371173/71632034-2228c080-2bc1-11ea-80cb-84dec92d2294.PNG">
<img width="545" alt="2" src="https://user-images.githubusercontent.com/57371173/71632035-248b1a80-2bc1-11ea-84dd-e413f1cde38f.PNG">

Will the next revision correct the above:
1. Show 100 Dens
2. Show #'s matching PKHeX
3. Show the Missing Den 16

I was trying to hunt this Den 16 as it is the ONLY spot in the game that spawns in Purple Beams Nest #43.
