### ISSUE TITLE
Update Removed Den #'s

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/PKHeX_Raid_Plugin#16]
Hello Leanny,

You seemed to miss the primary concern entirely with this update. The issue WAS NOT that the drop-down showed the individual Dens' numbers. _(We were ALL HAPPY about that as PKHeX recently added the Raid Parameter Editor features in the December 26th update.)_ The issue we all had is because your list was missing the "Watchtower Lair" (as the game names in the in-game descriptions) that the numbering was off.

The NEW issue created is that the drop-down no longer shows the Den numbers at all!

For example, let's say I wanted to find the following Den in the Raid Parameter Editor... now I have to scroll through the SEED's:

![image](https://user-images.githubusercontent.com/57371173/71644051-2f07eb80-2c77-11ea-8f1f-85e2b52658ec.png)

It is VITAL that the Raid List viewer's drop-down lists the Dens by the Den number SHOWN in the Raid Parameter Editor.

EXAMPLE:
![image](https://user-images.githubusercontent.com/57371173/71644140-8a86a900-2c78-11ea-9f34-705bf343d75b.png)
I have low Shiny Frame Advancement and want to use the Raid Parameter Editor to make the Den Active (since doing so in PKHeX doesn't re-roll the Shiny Frame Advancement.) How do you find that Den in the Raid Parameter Editor in a timely manner _**(when compared to how FAST it was in the previous version looking by Den number!!!)**_???

To conclude: all the active Issue posts you just closed were complaining that the number was off by 1 (because of the Missing Watchtower Lair location) NOT that you were using numbers. We want the drop-down for your Raid Viewer to be identical to the Raid Parameter Editor's drop-down!

**Comment by Th3Alic3** [comment]
(I've reverted to the previous version because this new one's drop-down is slowing me down tooooo much.)

**Comment by Leanny** [comment]
My bad. The numbers were removed by accident when I copied over the new names. I will create a hotfix version that has the numbers in it as well
