### ISSUE TITLE
Seed/frame problem

### ISSUE THREAD

**Issue by muchacho12** [Leanny/PKHeX_Raid_Plugin#17]
I encounter this last night. I threw a wp on my desired den (den50 bridge field 2), the after i got my purple beam I save the game closed it and back it up. Open my pkhex check the den and raid calculator i saw my den and mu shiny was on 208 frames, i did rng now on my switch checked it again and now its on 186 after 30 more frames i checked it again and it was gone. When i looked up on it i saw that it was on 6133 frame but all i did was spam the den using 1 day skipped method so what seems to be the 
![E05DB168-8E67-4EF8-80EE-B6D4E72E06C6](https://user-images.githubusercontent.com/59208234/71712069-a20f8e80-2e3e-11ea-8421-2d6e57937d85.jpeg)
![2A4227EC-A472-4E52-B7B9-53F889BF4EE1](https://user-images.githubusercontent.com/59208234/71712070-a2a82500-2e3e-11ea-95f7-7a288b909157.jpeg)
![Uploading 35A92810-0051-4E9F-B688-E79395B6E21A.jpeg…]()

problem?

**Comment by muchacho12** [comment]
Also i checked that the ability changes
![986017FA-05F3-4796-A83D-FCA4B006B909](https://user-images.githubusercontent.com/59208234/71712133-d71be100-2e3e-11ea-8812-b1bfee469f0d.jpeg)

**Comment by kwsch** [comment]
Those are totally different seeds you've selected.

Without seeing full screenshots (pls use PrintScreen instead of taking photos with your phone), can't really tell unless you're not entering in your data correctly. The bottom most screenshot has a 3\* Hatterene, while the top one is 5\*.
