### ISSUE TITLE
Meowstic Hidden Ability Missing

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/PKHeX_Raid_Plugin#18]
Hey Leanny,

The datamines originally shared by Kurt and listed on sites like Serebii.net list Meowstic access to it's Hidden Ability as YES (for both Genders as they are split between the versions.)

The search does not allow for a Hidden Ability parameter in the search.

![image](https://user-images.githubusercontent.com/57371173/71772548-acdf2780-2f01-11ea-916b-fcc4b216904a.png)

(Side note: if you could add something like "(Hidden)" after the abilities that appear in the Raid Viewer that would be amazing.)

**Comment by Leanny** [comment]
This is correct.
You can check serebii as reference: https://serebii.net/swordshield/maxraidbattles/den2.shtml
This is the only den where Meowstic is found and it does not give the Hidden Ability. 

This seems to be an error in the original datamine and serebii, as espurr is listed as having no access to HA (which is strange when Meowstic can get and pass it by breeding it).

I will add (1) / (2) / (Hidden) in the next version update
