### ISSUE TITLE
Can't find .dll file.

### ISSUE THREAD

**Issue by xCayde-6** [Leanny/PKHeX_Raid_Plugin#2]
Hi, you'll have to forgive me if this comes across as stupid haha I'm relatively new to the github scene. I have downloaded the latest release and extracted but I can't seem to find the .dll file. I have tried every way of putting the files in the plugins\ folder but nothing. Not even an error code.

I'm using the latest version of PKHex being 19.12.09.
I'm not sure if i'm missing certain files or plugins to read the main raid files.

**Comment by Leanny** [comment]
There is a release tab on github where you can find the dll: https://github.com/Leanny/PKHeX_Raid_Plugin/releases
