### ISSUE TITLE
[Request] Wild Area News Nests

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/PKHeX_Raid_Plugin#20]
Hello Leanny,

At this point in the future, will the Raid Viewer be able to displaying the Wild Area News Nests based upon the downloaded data? _(There is no shortage of people able to confirm the Nest Reports are contained in the save file - ie https://twitter.com/SciresM/status/1211897924872884224.)_ At this time, the Plug-In is not referencing this data but instead, it appears to be from a database you are programming.

The rate in which the Wild Area News is updating seems to be a faster pace than you are able to maintain. For example:

The Nest in this Den contains a Snorlax (NOT a Magikarp). The Magikarp New Year's event is over and as such Magikarp is not in the Wild Area News Nests anymore.
![image](https://user-images.githubusercontent.com/57371173/71797934-ffedd300-3004-11ea-9b4e-1f019cd8d7e5.png)

This makes it hard to RNG for the correct Pokemon when the Plug-In does not receive updates at a more frequent pace (which none of us expect.)

Instead, in the long-term, it would be best for the Plug-In to reference nest data for the event nests from the save file as it would never be out-of-date.

**Comment by rishik111** [comment]
Similarly, there are a few off-by-one issues when evaluating the Pokemon in a raid using the RandRoll value, even for non-event raids. This is particularly noticeable for the very rare Pokemon, such as Sirfetched, whose RandRoll value 1 greater than the plugin thinks it is.

**Comment by Leanny** [comment]
> There is no shortage of people able to confirm the Nest Reports are contained in the save file

Unfortunately they are not in the base savegame but more in a global switch save (bcat), which is not easily accessible by most savegame dumpers. Then the bcat save needs to be converted from the flatbuffer format to something I can work with, so it's a bit more work. I do have an idea on how to make it easier to update. I will work on this next.

> Similarly, there are a few off-by-one issues when evaluating the Pokemon in a raid using the RandRoll value, even for non-event raids.

This is an off-by-one error. I will fix it in the next commit

**Comment by Th3Alic3** [comment]
Checkpoint does not back-up that data? _(I have been able to restore earlier saves with now rotated out events - ie Christmas Delibird. What am I missing in my understanding?)_

**Comment by Leanny** [comment]
There might be some details stored in ``poke_trade`` or in the savegame, but the whole encounter table is not stored there. I just tested the latest version of checkpoint and it is not able to backup and restore BCAT saves.

**Comment by Th3Alic3** [comment]
Is the "Current" or "Lastest" encounter table in the `main` or `poke_trade`?

There has to be something in the save since I am able to revert back to the Christmas Delibird (which is not as useful as I originally was hoping since the Stamps do not appear to be receivable by any system with a newer update of the Wild Area News download.

So, Sword and Shield are storing some kind of master list of all the history of downloaded Nests deep in this `BCAT` save file?

**Comment by PP-theSLAYER** [comment]
Sorry to bump this thread, but I wanted to request the same thing, with relevant info to share.

The encounters _are_ stored in the _main_ save. With PKHeX, you can export the block that has the encounters, and read the species and the chance. (block info [here](https://projectpokemon.org/home/forums/topic/56121-swsh-blocks-and-save-research/))

However, the offsets between species and % chance is not consistent.
I'm giving your a file that should have the relevant offsets.
Important to note that everything on normal_encount file seems to be in reverse order.
That means you'll encounter slot 6 of SH 5* first. (I've labelled accordingly in the spreadsheet) [Note that the offsets are for the normal_encount file, not the save.]
[normal_encount_offsets.xlsx](https://github.com/Leanny/PKHeX_Raid_Plugin/files/4135614/normal_encount_offsets.xlsx)

**Comment by Leanny** [comment]
I will add this early February
