### ISSUE TITLE
Den #1: Wrong %'s

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/PKHeX_Raid_Plugin#21]
![image](https://user-images.githubusercontent.com/57371173/72226823-374f0900-354a-11ea-80c0-b9925083c347.png)

![image](https://user-images.githubusercontent.com/57371173/72226842-741b0000-354a-11ea-9f4e-b84a01dfd9c8.png)

The percentages appear to be off (at least for Den 1.)
I currently have a Nincada active on my screen in-game.
Drilbur's appearance is a range of 91 to 100.

I do know that PKHeX's hint note about Pokemon Percentile ranging from 0-99 is not accurate. The game's code is a range of: 1-100! The game may roll from 0-99 treating 0 as a roll of 100 but nonetheless the encounter per Pokemon Percentile tables definitely use a value range of 1-100!

**Comment by Leanny** [comment]
Please submit an issue here: https://github.com/kwsch/PKHeX
This is an issue with PKHeX, not an independent plugin

**Comment by Th3Alic3** [comment]
THIS:
![image](https://user-images.githubusercontent.com/57371173/72281995-99fae000-35f0-11ea-88f0-6b9d41c52a5c.png)

is an issue with THE PLUG-IN.

The PLUG-IN is showing the WRONG POKEMON. The encounter tables are stored in the PLUG-IN!
