### ISSUE TITLE
Method PKHeX.Core.SAV8SWSH.get_Blocks() missing in new PKHeX update

### ISSUE THREAD

**Issue by crzyc** [Leanny/PKHeX_Raid_Plugin#24]
![PKHeX_2020-01-26_06-49-33](https://user-images.githubusercontent.com/18177787/73134733-04a41680-4008-11ea-832c-de2177c88856.png)

Occurs on latest release of both plugin and PKHeX, and when I click "display raids".

**Comment by crzyc** [comment]
> Changed: Gen8 SWSH Block reading/writing is now much more efficient.

Related?

**Comment by Leanny** [comment]
Yeah, I need to recompile the plugin. I released a new version that is compatible with the latest release.

**Comment by crzyc** [comment]
Thanks!
