### ISSUE TITLE
Request: Forced Shiny Indicator

### ISSUE THREAD

**Issue by Th3Alic3** [Leanny/PKHeX_Raid_Plugin#27]
Hey Leanny!

Now that the Plug-in is reading from the Block Data, would you please add support to show indicators for the two following encounter flags:
01 - Cannot Be Shiny
02 - Forced Square Shiny

When you can!

Please and thanks!

**Comment by Leanny** [comment]
I wonder, what is the best way to display this? Should I maybe edit the image with specific symbols, or do you have a better idea?

**Comment by Th3Alic3** [comment]
I would likely just show it in the same spot you are already showing Shiny status. Use the same square symbol Kurt except have it the same color as the shiny star you are using. Then have a separate square symbol (maybe green) so it stands out. In that scenario, if you are using the color green for forced, I would use red for the non-shiny symbol: the classic red "X".

This would enhance your preview to show the difference between Shiny and Shiny Square in addition to the forced Shiny Square.

**Comment by Leanny** [comment]
I probably have an idea for this now, thank you. I will work on it and its hopefully in the next release

**Comment by Leanny** [comment]
Note: No Shiny is displayed in the image, forced shiny squares are only written as text. I might add some visual stuff for it at a later time, but for now I keep it to text only
