### ISSUE TITLE
Den Number Mismatch

### ISSUE THREAD

**Issue by RecycledName** [Leanny/PKHeX_Raid_Plugin#3]
The den number of the drop down doesn’t seem to match the location description and spawn. So far I’ve experienced it for Den 2 when the spawn and description for Den 37. Den 31 was also incorrect, I think it was Den 5 that had the matching location and spawn.

**Comment by Leanny** [comment]
They mismatch from what? I use the internal order here and print the location so people know where to look for them.

If you compare them to serebii, then serebii has the name wrong. Den = the thing you talk to, Nest = the encounters inside a den (which is what serebii labels as Den)

**Comment by RecycledName** [comment]
My mistake, I always see people referring to the spawn point by its Serebii den number so I thought that what was the tool was intended to reference.
