### ISSUE TITLE
Den Search isn't working on OFW save.

### ISSUE THREAD

**Issue by glong279** [Leanny/PKHeX_Raid_Plugin#34]
Hi Leanny. I'm having trouble opening the plugin when I'm using PKHeX to view my OFW save. It's like most problems reported before where I got that error when I open Den Search, except that I'm using latest versions of everything. It works perfectly fine on my save in CFW, but the OFW save just won't work. My guess is probably because of preload data of the DLC. Should I delete the DLC and redownload later for it to work?

Link to my save file: https://drive.google.com/file/d/1rHHb_IYJmoKEYTdw9zquzMPDF6mSb3K8/view?usp=sharing

**Comment by Leanny** [comment]
Sorry for the super late response. I cannot reproduce this issue with the current development version, so I guess its fixed. I will push the new version in a bit

**Comment by glong279** [comment]
Thank you for the reply. I got it working.
