### ISSUE TITLE
Link to guide is broken EOM

### ISSUE THREAD

**Issue by realquantumsource** [Leanny/PKHeX_Raid_Plugin#39]
Can you point to the right location, I wanna no what ec and pid mean in the seedfinder

**Comment by AnthonieZ87** [comment]
![image](https://user-images.githubusercontent.com/84002494/171941655-60d9a244-c268-46a4-858e-ccd8663b7d5e.png)

![image](https://user-images.githubusercontent.com/84002494/171941864-2f9b8662-eda0-4639-8961-d602b4a8d59e.png)
