### ISSUE TITLE
Error running "display raids" on latest pkhex and raid plugin.dll

### ISSUE THREAD

**Issue by zannki** [Leanny/PKHeX_Raid_Plugin#46]
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX_Raid_Plugin.RaidTemplateExtensions.ConvertToPKM(RaidTemplateTable[] denDetails, RaidParameters raidParameters, UInt64 hash, UInt32 TID, UInt32 SID)
   at PKHeX_Raid_Plugin.RaidManager.GenerateFromIndex(RaidParameters raidParameters)
   at PKHeX_Raid_Plugin.RaidList.LoadDen(RaidParameters raidParameters)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at PKHeX_Raid_Plugin.RaidList..ctor(SaveBlockAccessor8SWSH blocks, GameVersion game, Int32 badges, Int32 tid, Int32 sid)
   at PKHeX_Raid_Plugin.RaidPlugin.Open()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=20.6.22.0, Culture=neutral, PublicKeyToken=null
C:\Users\Zann\Desktop\PKHeX\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX_Raid_Plugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Zann\Desktop\PKHeX\plugins\PKHeX_Raid_Plugin.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by Leanny** [comment]
Not reproduceable on my end. Can you upload the savefile?

**Comment by zannki** [comment]
You mean my pokemon save file main file?

**Comment by Leanny** [comment]
Yeah the main file you used. I will try to reproduce it with the savefile

**Comment by edwarbad23** [comment]
I have that problem too, but happens when I put other seed

My log:
- Open Pkhex 
- put my save (without edit yet) > Display Raid work perfectly
- Edit seed in Pkhex and go to Display Raid> Error

**Comment by zannki** [comment]
> Yeah the main file you used. I will try to reproduce it with the savefile

Ok here is the save file. Btw, i can open display raids fine before laoding the savefile.
[https://drive.google.com/file/d/1GZkAnm92LqicGEVEo11Sqtz6o5_x_AL8/view?usp=sharing](url)

**Comment by edwarbad23** [comment]
> > Yeah the main file you used. I will try to reproduce it with the savefile
> 
> Ok here is the save file. Btw, i can open display raids fine before loading the savefile.
> 
> https://drive.google.com/file/d/1GZkAnm92LqicGEVEo11Sqtz6o5_x_AL8/view?usp=sharing

try to "active all" den option in pkhex and then try again!!

**Comment by zannki** [comment]
> > > Yeah the main file you used. I will try to reproduce it with the savefile
> > 
> > 
> > Ok here is the save file. Btw, i can open display raids fine before loading the savefile.
> > https://drive.google.com/file/d/1GZkAnm92LqicGEVEo11Sqtz6o5_x_AL8/view?usp=sharing
> 
> try to "active all" den option in pkhex and then try again!!

hey, it works!! Thanks man, i'll try testing it more.

**Comment by edwarbad23** [comment]
> > > > Yeah the main file you used. I will try to reproduce it with the savefile
> > > 
> > > 
> > > Ok here is the save file. Btw, i can open display raids fine before loading the savefile.
> > > https://drive.google.com/file/d/1GZkAnm92LqicGEVEo11Sqtz6o5_x_AL8/view?usp=sharing
> > 
> > 
> > try to "active all" den option in pkhex and then try again!!
> 
> hey, it works!! Thanks man, i'll try testing it more.

This is not the "properly" works but Idk why after we did this to works, I hope Leanny check the save and give us a reason why can't use display raids without active all den.

I assume you saved your game after of dlc

**Comment by zannki** [comment]
@edwarbad23 yes i did save at the dlc island. Maybe its got to do with older activated den. As long as it works is fine tho. All the activated den will be gone after raiding one den right.

**Comment by Leanny** [comment]
Activate All sets them to normal dens, not event dens. There was an issue that events on the basegame are loaded wrong when no nest update since the release of IoA has been done
