### ISSUE TITLE
Raid Seeds in checker don’t match the in game stats

### ISSUE THREAD

**Issue by KaiserTialoc** [Leanny/PKHeX_Raid_Plugin#47]
Hi,

I have checked the raid seed a few time for a 6iv Modest HA Square Shiny seed and the raid checker says it’s fine but the Pokémon caught in shield is from that seed is a 0iv calm nature

Is this a problem because of the new DLC release

Many thanks,
Connor

**Comment by Leanny** [comment]
Can you write what exactly you did so I can try to confirm it?

**Comment by KaiserTialoc** [comment]
So I used a raid seed that was meant to be for a 6iv Square Shiny Hidden ability Modest Pokémon which was DF5B0E17C2481578, and on your raid seed checker it said the same details as I mentioned however when I ran the raid myself and checked it the Pokémon was Square Shiny HA 1IV Hasty natured, I then used a few other seeds to check and even had the program generate the seeds it self and used one for as close a match as I could get and it instead had the Pokémon as a 0iv timid nature

**Comment by Leanny** [comment]
Raid mechanics are unchanged. This is a user issue. Seeds have different results on different targets. If you get a 1IV mon, then you are doing a 1-2 star raid. Your seed gives you a 6IV Square Shiny HA Modest mon for a 4IV base mon that can have all 3 abilities. If you saved the seed then you are able to see the results with the plugin immediately. Here a few examples:
3IV Base:
![2020-06-28 11_44_09-Window](https://user-images.githubusercontent.com/1884062/85944159-01091880-b935-11ea-8234-9b739bb4710a.png)

4IV Base with all abilities available:
![2020-06-28 11_46_53-Window](https://user-images.githubusercontent.com/1884062/85944178-1716d900-b935-11ea-9f66-d08ad8387315.png)

4IV Base with HA only:
![2020-06-28 11_47_35-Window](https://user-images.githubusercontent.com/1884062/85944192-331a7a80-b935-11ea-90a5-7c6845c0baa3.png)

5IV Base (Event):
![2020-06-28 11_48_14-Window](https://user-images.githubusercontent.com/1884062/85944205-49c0d180-b935-11ea-95e5-451c63306317.png)

As you can see the same seed results in all kind of different results. You need to use a seed that matches your target mon and not a random other mon that can be your target.

**Comment by KaiserTialoc** [comment]
<img width="295" alt="raid den seed mismatch" src="https://user-images.githubusercontent.com/67152067/86168906-b9d77f00-bb10-11ea-817e-5891099e7b23.PNG">
so i was using raid den 26 for the pirple beam and as you can see it shows the same info as you had above, all 6 IV's, Modest Nature, Square Shiny and Hidden Ability however the only thing that transferred into the den was the HA & Shinyness the IV's and Nature seemed to be randomised when it was caught in game
so im unsure whether this means the recent game update has done something to the seeds or if there is another issue

**Comment by Leanny** [comment]
I just injected the seed into my savegame and caught the mon. It was a 6iv modest HA gmax kingler, so I can say at least that nothing changed. Do you mind sending me your savegame (the one you use for this) so I can check if something is wrong with the savegame?

**Comment by KaiserTialoc** [comment]
Hi I have tried using another seed by searching for a square shiny HA seed using your raid seed calculator and relaunched and the results were the same.

i have attached a folder with the save game data plus the screen shots

Many Thanks again for looking into this
[pokemon seed mismatch.zip](https://github.com/Leanny/PKHeX_Raid_Plugin/files/4860572/pokemon.seed.mismatch.zip)

**Comment by Leanny** [comment]
Now things get strange. I injected the save and verified via capture sight + I caught the mon and the stats were as on the screen. Now I wonder, do you maybe have some atmosphere cheat codes/romfs edits enabled? Do you get the same results when you try it on vanilla firmware?

**Comment by KaiserTialoc** [comment]
oooooh now you mention, i have changed the Kingler to a GMAX Blastoise for den 26 because i didnt know which den is the isle of armor one on PKNX, even with that change how comes it makes the seed not work? i did change the den details to 6iv HA on PKNX but it didnt over ride it or anythin

i have attached the hacked folder if you want to look at it, i have left it with the Sword name just for convenience

[0100ABF008968000.zip](https://github.com/Leanny/PKHeX_Raid_Plugin/files/4866400/0100ABF008968000.zip)

**Comment by Leanny** [comment]
I suggest looking at https://leanny.github.io/seedchecker/#/dens/ for figuring out what den has what

I checked your file and the blastoise edit really is the reason why this doesnt work. To be a bit more precise: you fixed the 31IVs to 6. Hence it wont roll for IVs and go straight for nature. This is why it looks random to you

**Comment by KaiserTialoc** [comment]
Ahhh so if I reset the file for it and only change the Pokémon to Blastoise the seed should work correctly?
Thanks again for all your help, not many people can answer questions like this for me

**Comment by Leanny** [comment]
It should work then, yeah. You can try to catch it on vanilla fw and check nature + ivs first to confirm that the seed results in what you want
