### ISSUE TITLE
Can I ask you a question？

### ISSUE THREAD

**Issue by CScorpion-h** [Leanny/PKHeX_Raid_Plugin#52]
I compiled the latest pkhex and raid plugin. When I opened PKHEX, I didn't see the raid plugin.
And Also I placed Microsoft.Z3.dll and libz3.dll in the same folder as PKHeX.
I didn't know if I made a mistake or if pkhex did not load the plugin. Can you try it if it is convenient for you?

**Comment by Leanny** [comment]
The plugin will be in its own project. You need to copy it from the raid plugin project to the pkhex build by yourself

**Comment by CScorpion-h** [comment]
> The plugin will be in its own project. You need to copy it from the raid plugin project to the pkhex build by yourself

It means that I need to import it(dll) before compiling pkhex?

**Comment by Leanny** [comment]
It means that after you build the plugin, you will get a dll file. Then you copy this dll file into the plugins folder in pkhex. See this part: https://github.com/Leanny/PKHeX_Raid_Plugin#installation

**Comment by CScorpion-h** [comment]
> It means that after you build the plugin, you will get a dll file. Then you copy this dll file into the plugins folder in pkhex. See this part: https://github.com/Leanny/PKHeX_Raid_Plugin#installation

Yeah, I did it but I didn't see the plugin on pkhex.  
After I compiled the plugin, I put it in the plugins/ directory of PKHEX.And then I placed Microsoft.Z3.dll and libz3.dll in the same folder as PKHeX.
It didn't work, I don't know why.It's weird.

**Comment by CScorpion-h** [comment]
> It means that after you build the plugin, you will get a dll file. Then you copy this dll file into the plugins folder in pkhex. See this part: https://github.com/Leanny/PKHeX_Raid_Plugin#installation

I found that the plugin is not loaded on Debug.

**Comment by AnthonieZ87** [comment]
Did u try unblocking the plug?
go to plugin directory, click it, right click it, check unblock, click ok
open pkhex
