### ISSUE TITLE
Crash upon opening Raid Calculator

### ISSUE THREAD

**Issue by kaelmoreno-cp** [Leanny/PKHeX_Raid_Plugin#60]
I opened a savefile to PkHex, but open clicking Raid Calculator of a Crown Tundra den, this error showed:

![image](https://user-images.githubusercontent.com/7289423/97098648-4b6b8d80-16ba-11eb-9cb4-37941b0d0802.png)

I read the changelog for the latest release, and I believe the only thing left for your implementation is the map, so I assumed that Raid Calculator works now. Just want to know if its supported now?

Thank you for always doing and updating this! Its really a big help for us :)

**Comment by Leanny** [comment]
Oops, forgot one thing. I replaced the release in the Release Tab. Can you try it again?

**Comment by Xsalta** [comment]
I have just tried the replaced version that you have just put in the Release Tab and I seem to be getting this same issue.
Is the correct there now? Btw, thanks for all your hard work!

**Comment by EsteeMcCrawly** [comment]
I just used the dll file and it is giving me the same error. I even deleted and redownloaded but same issue.

**Comment by Leanny** [comment]
I did a little oopsi there. Can you try to re-download it again now? Just in case I uploaded the wrong file again, here are the stats:
Old:
SHA1: 18FAC287386EAD97A42E31A424E76D9D96810107
File Size: 2097664 Bytes (2048 KiB)

New (correct) one:
SHA1: B5A5E14BE3D7645F3C6C084099CFF120343F729E
File Size: 2098688 Bytes (2049 KiB)

**Comment by Xsalta** [comment]
Was having the same issue myself earlier, the raid calculator works for me now. Thank you!

**Comment by EsteeMcCrawly** [comment]
This new one doesnt have the Crown Tundra dens at all, just base and IOA.

**Comment by Leanny** [comment]
Are you sure you use the correct one? https://github.com/Leanny/PKHeX_Raid_Plugin/releases/download/1.8-pre/PKHeX_Raid_Plugin.dll

**Comment by EsteeMcCrawly** [comment]
I was sure but I guess i pulled a noob move. It's working now, thanks!

**Comment by kaelmoreno-cp** [comment]
Its working now, @Leanny ! Thank you!

![image](https://user-images.githubusercontent.com/7289423/97134013-cdc18380-1786-11eb-931c-2522071aa05f.png)

**Comment by kaelmoreno-cp** [comment]
Closing this issue now :)
