### ISSUE TITLE
1/2 star

### ISSUE THREAD

**Issue by drewlobel** [Leanny/PKHeX_Raid_Plugin#71]
Im not sure if i am doing somethin wrong when I use the plugin on PKHeX i dont see 1/2 star raids. thx

**Comment by Leanny** [comment]
"Baby" raids are only available when you have barely badges. This plugin ensures that you only set/see legal raids, so the option for stars that you cannot encounter anymore is not listed

**Comment by xxxdrewwerdxx** [comment]
Ok that makes senses. Thank you

On Sun, Jun 27, 2021 at 14:35 Leanny ***@***.***> wrote:

> "Baby" raids are only available when you have barely badges. This plugin
> ensures that you only set/see legal raids, so the option for stars that you
> cannot encounter anymore is not listed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLeanny%2FPKHeX_Raid_Plugin%2Fissues%2F71%23issuecomment-869213949&data=04%7C01%7C1046403%40locker.lcps.org%7Cf7d3c8f7d6864d47ae9c08d939a2baf7%7C86750b0cee12463db28880f7b2b34689%7C0%7C0%7C637604193358215324%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nQckFncxXjVYQuSy2zJ8txSnGAuIeKY5%2F8Mi7pEXn0s%3D&reserved=0>,
> or unsubscribe.
>
-- 
YIS,
Drew S Lobel
