### ISSUE TITLE
Using Z3

### ISSUE THREAD

**Issue by jjaldridge2009** [Leanny/PKHeX_Raid_Plugin#8]
Can you flesh out the instruction in the readme more, for "adding Z3/bin" to the path? I put the Z3.dll from the release you posted in the plugin directory, and added this to the "Target" line of my PkHex shortcut, but it did not work:

C:\PKHeX (191209)\PKHeX.exe" -Z3/bin

**Comment by kwsch** [comment]
Place the `PKHeX_Raid_Plugin.dll` in the "plugins" folder
Place the `Microsoft.Z3.dll` in the same folder as PKHeX.exe
Place the `libz3.dll` in the same folder as PKHeX.exe

**Comment by jjaldridge2009** [comment]
That did the trick. Thank you Kurt!
