### ISSUE TITLE
About NET7.0 and translations

### ISSUE THREAD

**Issue by ppllouf** [Leanny/PKHeX_Raid_Plugin#99]
When will NET 7.0 be updated?
Will you add language files like those PKHeX has to your plugins?
I will contribute to the translation of this plugin in Chinese:)

**Comment by Leanny** [comment]
I just merged the Request for .NET 7.0, so that should work now.

Unfortunately, I do not want to continue to develop this plugin, so adding support for different languages is not planned. But if someone else wants to maintain the plugin, then I will happily give them access

**Comment by ppllouf** [comment]
Okay! I'm glad to get your reply:)
